/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations["getHealthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Daemon metadata */
    get: operations["getInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/shutdown": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Graceful shutdown */
    post: operations["postShutdown"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Server-Sent Events stream */
    get: operations["getEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List images (paginated, filterable) */
    get: operations["listImages"];
    put?: never;
    /** Import images from paths */
    post: operations["importImages"];
    /** Delete images by id */
    delete: operations["deleteImages"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/import-web": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start web/URL import (async; progress via SSE) */
    post: operations["importWebImages"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Distinct tag list */
    get: operations["getImageTags"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Apply history */
    get: operations["getHistory"];
    put?: never;
    post?: never;
    /** Clear apply history */
    delete: operations["clearHistory"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/cancel-import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel in-flight import */
    post: operations["cancelImport"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/select-all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Select all ids matching current gallery query */
    post: operations["selectAllImages"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one image */
    get: operations["getImage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update image metadata; patching `name` atomically renames the file on disk */
    patch: operations["patchImage"];
    trace?: never;
  };
  "/images/{id}/ensure-browser-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate browser-playable video preview if missing */
    post: operations["ensureBrowserPreview"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/{id}/video-loop-export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Export seamless loop (async) */
    post: operations["videoLoopExport"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/{id}/extract-video-palette": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Extract dominant colors from one frame (same algorithm as still images); persists colors on the gallery row */
    post: operations["extractVideoPalette"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/{id}/thumbnail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Thumbnail (processed) */
    get: operations["getThumbnail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/images/{id}/raw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Full raw file */
    get: operations["getRawImage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listPlaylists"];
    put?: never;
    post: operations["createPlaylist"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/active": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listActivePlaylists"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/active/{monitor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getActiveByMonitor"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/active/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["stopAllPlaylists"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/active/pause": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["pauseAllPlaylists"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/active/resume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["resumeAllPlaylists"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/active/next": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["nextAllPlaylists"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/active/previous": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["previousAllPlaylists"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPlaylist"];
    put?: never;
    post?: never;
    delete: operations["deletePlaylist"];
    options?: never;
    head?: never;
    patch: operations["patchPlaylist"];
    trace?: never;
  };
  "/playlists/{id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["startPlaylist"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/{id}/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["stopPlaylist"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/{id}/pause": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["pausePlaylist"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/{id}/resume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["resumePlaylist"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/{id}/next": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["nextPlaylist"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/{id}/previous": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["previousPlaylist"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/folders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listFolders"];
    put?: never;
    post: operations["createFolder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/folders/move-images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["moveImages"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/folders/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getFolder"];
    put?: never;
    post?: never;
    delete: operations["deleteFolder"];
    options?: never;
    head?: never;
    patch: operations["patchFolder"];
    trace?: never;
  };
  "/folders/{id}/path": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getFolderPath"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/monitors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listMonitors"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/monitors/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getMonitor"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getConfig"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["patchConfig"];
    trace?: never;
  };
  "/config/{section}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getConfigSection"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["patchConfigSection"];
    trace?: never;
  };
  "/config/backends/{backend}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getNamedBackendConfig"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["patchNamedBackendConfig"];
    trace?: never;
  };
  "/backends": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listBackends"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backends/{name}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["activateBackend"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wallpaper/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Per-monitor (or global) current wallpaper state */
    get: operations["getWallpaperCurrent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wallpaper/set": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["setWallpaper"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wallpaper/random": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["randomWallpaper"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AutoPriorities: {
      image?: string[];
      video?: string[];
      web?: string[];
    };
    BackendSection: {
      type?: string;
      transition_duration_seconds?: number;
      selection_mode?: string;
      auto_priorities?: components["schemas"]["AutoPriorities"];
    };
    /** @description Application UI and gallery defaults (`internal/config.AppConfig`). */
    AppConfig: {
      [key: string]: unknown;
    };
    /** @description Paths, logging, compositor (`internal/config.DaemonConfig`). */
    DaemonConfig: {
      [key: string]: unknown;
    };
    MonitorsConfig: {
      [key: string]: unknown;
    };
    WallhavenConfig: {
      [key: string]: unknown;
    };
    /** @description Full config returned by GET /config; matches `config.Config` JSON tags. */
    UnifiedConfig: {
      app: components["schemas"]["AppConfig"];
      daemon: components["schemas"]["DaemonConfig"];
      backend: components["schemas"]["BackendSection"];
      monitors: components["schemas"]["MonitorsConfig"];
      wallhaven: components["schemas"]["WallhavenConfig"];
    };
    /** @description PATCH /config body — keys are TOML section names (`app`, `daemon`, …), values are partial objects merged per section. */
    PatchConfigRequest: {
      [key: string]: {
        [key: string]: unknown;
      };
    };
    /** @description JSON for one TOML section (not the top-level `backend` alias path). */
    ConfigSectionDocument: {
      [key: string]: unknown;
    };
    /** @description Partial fields for PATCH /config/{section}. */
    ConfigSectionPatchBody: {
      [key: string]: unknown;
    };
    /** @description Per-renderer JSON for GET|PATCH /config/backends/{backend}; shape depends on backend. */
    NamedBackendConfigBlob: {
      [key: string]: unknown;
    };
    NamedBackendPatchResponse: {
      /** @example updated */
      status: string;
    };
    BackendCapabilities: {
      compositors?: string[];
      media_types?: string[];
      transitions?: boolean;
      per_monitor?: boolean;
      daemon_process?: boolean;
    };
    BackendInfo: {
      name: string;
      available: boolean;
      capabilities?: components["schemas"]["BackendCapabilities"];
    };
    ActivateBackendResponse: {
      /** @enum {string} */
      status: "activated";
      backend: string;
    };
    /** @description Fallback for routes not yet split into dedicated components (gallery, playlists, …). */
    GenericJSON: {
      [key: string]: unknown;
    };
    StatusOk: {
      /** @example ok */
      status?: string;
    };
    /** @description See API_CONTRACT.md "Error format" */
    APIError: {
      error?: string;
      code?: number;
      details?: string;
    };
  };
  responses: {
    /** @description Not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["APIError"];
      };
    };
  };
  parameters: {
    Page: number;
    PerPage: number;
    ImageId: number;
    PlaylistIdPath: number;
    FolderIdPath: number;
    /** @description TOML section (e.g. `app`, `daemon`, `monitors`, `wallhaven`). The path value `backend` is reserved and returns 404; use `/config/backends/{backend}` for per-renderer JSON instead. */
    ConfigSectionPath: string;
    ConfigBackendNamePath: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusOk"];
        };
      };
    };
  };
  getInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Version, pid, host, runtime */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  postShutdown: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepting shutdown */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  getEvents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description text/event-stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  listImages: {
    parameters: {
      query?: {
        page?: components["parameters"]["Page"];
        per_page?: components["parameters"]["PerPage"];
        sort_by?: string;
        sort_order?: "asc" | "desc";
        media_type?: string;
        search?: string;
        tags?: string;
        colors?: string;
        colors_near?: string;
        /** @description Reference image id — keep rows whose palette is within ΔE of this image (CIE76, min pairwise swatch distance). */
        palette_similar_to?: number;
        /** @description Inclusive max ΔE (default 18 on daemon). */
        palette_max_delta_e?: number;
        folder_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paged list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  importImages: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      /** @description Processing */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  deleteImages: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      /** @description Count deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  importWebImages: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      /** @description Accepted or batch id */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getImageTags: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  getHistory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  clearHistory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  cancelImport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  selectAllImages: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  getImage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ImageId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  patchImage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ImageId"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  ensureBrowserPreview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ImageId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description In progress */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  videoLoopExport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ImageId"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Queued */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  extractVideoPalette: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ImageId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Timeline position in seconds (clamped to stream duration) */
          time_seconds?: number;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            colors: string[];
            image_id: number;
          };
        };
      };
    };
  };
  getThumbnail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ImageId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description image bytes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components["responses"]["NotFound"];
    };
  };
  getRawImage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ImageId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description binary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components["responses"]["NotFound"];
    };
  };
  listPlaylists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  createPlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  listActivePlaylists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  getActiveByMonitor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        monitor: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  stopAllPlaylists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  pauseAllPlaylists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  resumeAllPlaylists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  nextAllPlaylists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  previousAllPlaylists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  getPlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PlaylistIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  deletePlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PlaylistIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patchPlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PlaylistIdPath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  startPlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PlaylistIdPath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  stopPlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PlaylistIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  pausePlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PlaylistIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  resumePlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PlaylistIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  nextPlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PlaylistIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  previousPlaylist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PlaylistIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listFolders: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  createFolder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  moveImages: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getFolder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["FolderIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  deleteFolder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["FolderIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patchFolder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["FolderIdPath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  getFolderPath: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["FolderIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  listMonitors: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  getMonitor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  getConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnifiedConfig"];
        };
      };
    };
  };
  patchConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchConfigRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnifiedConfig"];
        };
      };
    };
  };
  getConfigSection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description TOML section (e.g. `app`, `daemon`, `monitors`, `wallhaven`). The path value `backend` is reserved and returns 404; use `/config/backends/{backend}` for per-renderer JSON instead. */
        section: components["parameters"]["ConfigSectionPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigSectionDocument"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  patchConfigSection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description TOML section (e.g. `app`, `daemon`, `monitors`, `wallhaven`). The path value `backend` is reserved and returns 404; use `/config/backends/{backend}` for per-renderer JSON instead. */
        section: components["parameters"]["ConfigSectionPath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConfigSectionPatchBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigSectionDocument"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  getNamedBackendConfig: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        backend: components["parameters"]["ConfigBackendNamePath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NamedBackendConfigBlob"];
        };
      };
    };
  };
  patchNamedBackendConfig: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        backend: components["parameters"]["ConfigBackendNamePath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["NamedBackendConfigBlob"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NamedBackendPatchResponse"];
        };
      };
    };
  };
  listBackends: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackendInfo"][];
        };
      };
    };
  };
  activateBackend: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backend activated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivateBackendResponse"];
        };
      };
    };
  };
  getWallpaperCurrent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  setWallpaper: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
  randomWallpaper: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["GenericJSON"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenericJSON"];
        };
      };
    };
  };
}
