// AUTO-GENERATED by vite-plugin-theme-registry. Do not edit.
import type { BuiltinThemeMeta } from "./types";

import "./80s-vibe-light.css";
import "./80s-vibe.css";
import "./catppuccin-latte.css";
import "./catppuccin-mocha.css";
import "./dracula-light.css";
import "./everforest-light.css";
import "./everforest.css";
import "./gruvbox-light.css";
import "./gruvbox-material-light.css";
import "./gruvbox-material.css";
import "./gruvbox.css";
import "./kanagawa-light.css";
import "./kanagawa.css";
import "./kolision-raw-dark.css";
import "./kolision-raw.css";
import "./monokai-light.css";
import "./monokai.css";
import "./nord-light.css";
import "./nord.css";
import "./solarized-light.css";
import "./solarized.css";
import "./tokyo-night-light.css";
import "./tokyo-night.css";

export const builtInThemes: readonly BuiltinThemeMeta[] = [
  {
    name: "80s-vibe-light",
    displayName: "80s Vibe Light",
    category: "light",
    source: "builtin",
    sourceUrl: "internal:broadcast-midnight",
  },
  {
    name: "80s-vibe",
    displayName: "80s Vibe",
    category: "dark",
    source: "builtin",
    sourceUrl: "internal:broadcast-midnight",
  },
  {
    name: "catppuccin-latte",
    displayName: "Catppuccin Latte",
    category: "light",
    source: "builtin",
    sourceUrl: "https://catppuccin.com/palette",
  },
  {
    name: "catppuccin-mocha",
    displayName: "Catppuccin Mocha",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://catppuccin.com/palette",
  },
  {
    name: "dracula-light",
    displayName: "Dracula Light",
    category: "light",
    source: "builtin",
    sourceUrl: "https://draculatheme.com",
  },
  {
    name: "everforest-light",
    displayName: "Everforest Light",
    category: "light",
    source: "builtin",
    sourceUrl: "https://github.com/sainnhe/everforest",
  },
  {
    name: "everforest",
    displayName: "Everforest",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://github.com/sainnhe/everforest",
  },
  {
    name: "gruvbox-light",
    displayName: "Gruvbox Light",
    category: "light",
    source: "builtin",
    sourceUrl: "https://github.com/morhetz/gruvbox",
  },
  {
    name: "gruvbox-material-light",
    displayName: "Gruvbox Material Light",
    category: "light",
    source: "builtin",
    sourceUrl: "https://github.com/sainnhe/gruvbox-material",
  },
  {
    name: "gruvbox-material",
    displayName: "Gruvbox Material",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://github.com/sainnhe/gruvbox-material",
  },
  {
    name: "gruvbox",
    displayName: "Gruvbox",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://github.com/morhetz/gruvbox",
  },
  {
    name: "kanagawa-light",
    displayName: "Kanagawa Light",
    category: "light",
    source: "builtin",
    sourceUrl: "https://github.com/rebelot/kanagawa.nvim",
  },
  {
    name: "kanagawa",
    displayName: "Kanagawa",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://github.com/rebelot/kanagawa.nvim",
  },
  {
    name: "kolision-raw-dark",
    displayName: "Kolision Raw Dark",
    category: "dark",
    source: "builtin",
    sourceUrl: "internal:house-built",
  },
  {
    name: "kolision-raw",
    displayName: "Kolision Raw",
    category: "light",
    source: "builtin",
    sourceUrl: "internal:house-built",
  },
  {
    name: "monokai-light",
    displayName: "Monokai Light",
    category: "light",
    source: "builtin",
    sourceUrl: "https://monokai.pro",
  },
  {
    name: "monokai",
    displayName: "Monokai",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://monokai.pro",
  },
  {
    name: "nord-light",
    displayName: "Nord Light",
    category: "light",
    source: "builtin",
    sourceUrl: "https://www.nordtheme.com/docs/colors-and-palettes",
  },
  {
    name: "nord",
    displayName: "Nord",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://www.nordtheme.com/docs/colors-and-palettes",
  },
  {
    name: "solarized-light",
    displayName: "Solarized Light",
    category: "light",
    source: "builtin",
    sourceUrl: "https://ethanschoonover.com/solarized",
  },
  {
    name: "solarized",
    displayName: "Solarized",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://ethanschoonover.com/solarized",
  },
  {
    name: "tokyo-night-light",
    displayName: "Tokyo Day",
    category: "light",
    source: "builtin",
    sourceUrl: "https://github.com/folke/tokyonight.nvim",
  },
  {
    name: "tokyo-night",
    displayName: "Tokyo Night",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://github.com/folke/tokyonight.nvim",
  },
] as const;
