// AUTO-GENERATED by vite-plugin-theme-registry. Do not edit.
import type { BuiltinThemeMeta } from "./types";

import "./nord-light.css";
import "./nord.css";

export const builtInThemes: readonly BuiltinThemeMeta[] = [
  {
    name: "nord-light",
    displayName: "Nord Light",
    category: "light",
    source: "builtin",
    sourceUrl: "https://www.nordtheme.com/docs/colors-and-palettes",
  },
  {
    name: "nord",
    displayName: "Nord",
    category: "dark",
    source: "builtin",
    sourceUrl: "https://www.nordtheme.com/docs/colors-and-palettes",
  },
] as const;
