import { promises as fs } from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";

interface HeaderMeta {
  name: string;
  displayName: string;
  category: "light" | "dark" | "mixed";
  sourceUrl?: string;
}

const HEADER_RE = /\/\*\s*@waypaper-theme\s*\n([\s\S]*?)\*\//;

function parseHeader(css: string): HeaderMeta | null {
  const m = css.match(HEADER_RE);
  if (!m) return null;
  const lines = m[1]
    .split("\n")
    .map((l) => l.replace(/^\s*\*?\s?/, "").trim())
    .filter(Boolean);
  const fields: Record<string, string> = {};
  for (const line of lines) {
    const eq = line.indexOf(":");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    fields[key] = value;
  }
  if (!fields.name || !fields.displayName || !fields.category) return null;
  return {
    name: fields.name,
    displayName: fields.displayName,
    category: fields.category as HeaderMeta["category"],
    sourceUrl: fields.sourceUrl,
  };
}

export function themeRegistryPlugin(opts: {
  themesDir: string;
  outFile: string;
}): Plugin {
  const { themesDir, outFile } = opts;
  const outDir = path.dirname(outFile);

  async function generate() {
    const entries = (await fs.readdir(themesDir))
      .filter((f) => f.endsWith(".css") && !f.startsWith("_"))
      .sort();
    const metas: Array<HeaderMeta & { file: string }> = [];
    const cssChunks: string[] = [];
    for (const file of entries) {
      const css = await fs.readFile(path.join(themesDir, file), "utf8");
      const meta = parseHeader(css);
      if (!meta) {
        // eslint-disable-next-line no-console
        console.warn(
          `[theme-registry] ${file} missing @waypaper-theme header — skipped`,
        );
        continue;
      }
      metas.push({ ...meta, file });
      cssChunks.push(css);
    }

    const importLines = metas.map((m) => `import "./${m.file}";`).join("\n");
    const arrayBody = metas
      .map(
        (m) =>
          `  { name: ${JSON.stringify(m.name)}, ` +
          `displayName: ${JSON.stringify(m.displayName)}, ` +
          `category: ${JSON.stringify(m.category)}, ` +
          `source: "builtin"` +
          (m.sourceUrl ? `, sourceUrl: ${JSON.stringify(m.sourceUrl)}` : "") +
          ` }`,
      )
      .join(",\n");

    const tsOut =
      `// AUTO-GENERATED by vite-plugin-theme-registry. Do not edit.\n` +
      `import type { BuiltinThemeMeta } from "./types";\n\n` +
      (importLines ? importLines + "\n\n" : "") +
      `export const builtInThemes: readonly BuiltinThemeMeta[] = [\n${arrayBody ? arrayBody + ",\n" : ""}] as const;\n`;

    const existingTs = await fs.readFile(outFile, "utf8").catch(() => "");
    if (existingTs !== tsOut) await fs.writeFile(outFile, tsOut, "utf8");

    // Bundled CSS — concatenate all palette files so Tailwind v4 / DaisyUI
    // can pick up every @plugin block through a single CSS @import.
    const cssIndexPath = path.join(outDir, "_index.css");
    const cssOut =
      `/* AUTO-GENERATED by vite-plugin-theme-registry. Do not edit. */\n` +
      cssChunks.join("\n");
    const existingCss = await fs.readFile(cssIndexPath, "utf8").catch(() => "");
    if (existingCss !== cssOut) await fs.writeFile(cssIndexPath, cssOut, "utf8");
  }

  return {
    name: "waypaper:theme-registry",
    async buildStart() {
      await generate();
    },
    configureServer(server) {
      server.watcher.add(themesDir);
      const onChange = (file: string) => {
        if (file.startsWith(themesDir) && file.endsWith(".css")) generate();
      };
      server.watcher.on("add", onChange);
      server.watcher.on("unlink", onChange);
      server.watcher.on("change", onChange);
    },
  };
}
