// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Activeplaylist struct {
	Playlistid        int64  `json:"playlistid"`
	Activemonitor     string `json:"activemonitor"`
	Activemonitorname string `json:"activemonitorname"`
}

type Appconfig struct {
	Config string `json:"config"`
}

type Image struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Ischecked  int64  `json:"ischecked"`
	Isselected int64  `json:"isselected"`
	Width      int64  `json:"width"`
	Height     int64  `json:"height"`
	Format     string `json:"format"`
}

type Imagehistory struct {
	Imageid int64          `json:"imageid"`
	Monitor string         `json:"monitor"`
	Time    sql.NullString `json:"time"`
}

type Imagesinplaylist struct {
	Imageid         int64         `json:"imageid"`
	Playlistid      int64         `json:"playlistid"`
	Indexinplaylist int64         `json:"indexinplaylist"`
	Time            sql.NullInt64 `json:"time"`
}

type Playlist struct {
	ID                      int64          `json:"id"`
	Name                    string         `json:"name"`
	Type                    string         `json:"type"`
	Interval                sql.NullInt64  `json:"interval"`
	Showanimations          int64          `json:"showanimations"`
	Alwaysstartonfirstimage int64          `json:"alwaysstartonfirstimage"`
	Order                   sql.NullString `json:"order"`
	Currentimageindex       int64          `json:"currentimageindex"`
}

type Selectedmonitor struct {
	Monitor string `json:"monitor"`
}

type Swwwconfig struct {
	Config string `json:"config"`
}
