// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const addImageToHistory = `-- name: AddImageToHistory :exec
INSERT INTO imageHistory (imageID, monitor, time)
VALUES (?, ?, strftime('%s', 'now'))
`

type AddImageToHistoryParams struct {
	Imageid int64  `json:"imageid"`
	Monitor string `json:"monitor"`
}

func (q *Queries) AddImageToHistory(ctx context.Context, arg AddImageToHistoryParams) error {
	_, err := q.db.ExecContext(ctx, addImageToHistory, arg.Imageid, arg.Monitor)
	return err
}

const backupAppConfig = `-- name: BackupAppConfig :one
SELECT config FROM appConfig LIMIT 1
`

func (q *Queries) BackupAppConfig(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, backupAppConfig)
	var config string
	err := row.Scan(&config)
	return config, err
}

const backupSwwwConfig = `-- name: BackupSwwwConfig :one
SELECT config FROM swwwConfig LIMIT 1
`

func (q *Queries) BackupSwwwConfig(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, backupSwwwConfig)
	var config string
	err := row.Scan(&config)
	return config, err
}

const checkImageInHistory = `-- name: CheckImageInHistory :one
SELECT COUNT(*) as count
FROM imageHistory
WHERE imageID = ? AND monitor = ?
`

type CheckImageInHistoryParams struct {
	Imageid int64  `json:"imageid"`
	Monitor string `json:"monitor"`
}

func (q *Queries) CheckImageInHistory(ctx context.Context, arg CheckImageInHistoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkImageInHistory, arg.Imageid, arg.Monitor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const cleanupImageHistory = `-- name: CleanupImageHistory :exec
DELETE FROM imageHistory
WHERE (imageID, monitor, time) NOT IN (
    SELECT imageID, monitor, time FROM imageHistory
    ORDER BY time DESC
    LIMIT ?
)
`

func (q *Queries) CleanupImageHistory(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, cleanupImageHistory, limit)
	return err
}

const clearImageHistory = `-- name: ClearImageHistory :exec
DELETE FROM imageHistory
`

func (q *Queries) ClearImageHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearImageHistory)
	return err
}

const clearImageHistoryByMonitor = `-- name: ClearImageHistoryByMonitor :exec
DELETE FROM imageHistory
WHERE monitor = ?
`

func (q *Queries) ClearImageHistoryByMonitor(ctx context.Context, monitor string) error {
	_, err := q.db.ExecContext(ctx, clearImageHistoryByMonitor, monitor)
	return err
}

const createImage = `-- name: CreateImage :one
INSERT INTO Images (name, isChecked, isSelected, width, height, format)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, ischecked, isselected, width, height, format
`

type CreateImageParams struct {
	Name       string `json:"name"`
	Ischecked  int64  `json:"ischecked"`
	Isselected int64  `json:"isselected"`
	Width      int64  `json:"width"`
	Height     int64  `json:"height"`
	Format     string `json:"format"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.Name,
		arg.Ischecked,
		arg.Isselected,
		arg.Width,
		arg.Height,
		arg.Format,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ischecked,
		&i.Isselected,
		&i.Width,
		&i.Height,
		&i.Format,
	)
	return i, err
}

const deleteAppConfig = `-- name: DeleteAppConfig :exec
DELETE FROM appConfig
`

func (q *Queries) DeleteAppConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAppConfig)
	return err
}

const deleteImagesByIDs = `-- name: DeleteImagesByIDs :exec
DELETE FROM Images
WHERE id IN (/*SLICE:imageIDs*/?)
`

func (q *Queries) DeleteImagesByIDs(ctx context.Context, imageids []int64) error {
	query := deleteImagesByIDs
	var queryParams []interface{}
	if len(imageids) > 0 {
		for _, v := range imageids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:imageIDs*/?", strings.Repeat(",?", len(imageids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:imageIDs*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteMultipleImages = `-- name: DeleteMultipleImages :exec
DELETE FROM Images
WHERE name IN (/*SLICE:imageNames*/?)
`

// Bulk Operations for Performance
func (q *Queries) DeleteMultipleImages(ctx context.Context, imagenames []string) error {
	query := deleteMultipleImages
	var queryParams []interface{}
	if len(imagenames) > 0 {
		for _, v := range imagenames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:imageNames*/?", strings.Repeat(",?", len(imagenames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:imageNames*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deletePlaylistByID = `-- name: DeletePlaylistByID :exec
DELETE FROM Playlists
WHERE id = ?
`

func (q *Queries) DeletePlaylistByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlaylistByID, id)
	return err
}

const deletePlaylistByName = `-- name: DeletePlaylistByName :exec
DELETE FROM Playlists
WHERE name = ?
`

func (q *Queries) DeletePlaylistByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylistByName, name)
	return err
}

const deletePlaylistImages = `-- name: DeletePlaylistImages :exec
DELETE FROM imagesInPlaylist
WHERE playlistID = ?
`

func (q *Queries) DeletePlaylistImages(ctx context.Context, playlistid int64) error {
	_, err := q.db.ExecContext(ctx, deletePlaylistImages, playlistid)
	return err
}

const deleteSelectedMonitor = `-- name: DeleteSelectedMonitor :exec
DELETE FROM selectedMonitor
`

func (q *Queries) DeleteSelectedMonitor(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSelectedMonitor)
	return err
}

const deleteSwwwConfig = `-- name: DeleteSwwwConfig :exec
DELETE FROM swwwConfig
`

func (q *Queries) DeleteSwwwConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSwwwConfig)
	return err
}

const getActivePlaylistByMonitor = `-- name: GetActivePlaylistByMonitor :one
SELECT p.id, p.name, p.type, p.interval, p.showAnimations, p.alwaysStartOnFirstImage, p."order", p.currentImageIndex,
       ap.activeMonitor, ap.activeMonitorName
FROM Playlists p
INNER JOIN activePlaylists ap ON p.id = ap.playlistID
WHERE ap.activeMonitorName = ?
`

type GetActivePlaylistByMonitorRow struct {
	ID                      int64          `json:"id"`
	Name                    string         `json:"name"`
	Type                    string         `json:"type"`
	Interval                sql.NullInt64  `json:"interval"`
	Showanimations          int64          `json:"showanimations"`
	Alwaysstartonfirstimage int64          `json:"alwaysstartonfirstimage"`
	Order                   sql.NullString `json:"order"`
	Currentimageindex       int64          `json:"currentimageindex"`
	Activemonitor           string         `json:"activemonitor"`
	Activemonitorname       string         `json:"activemonitorname"`
}

func (q *Queries) GetActivePlaylistByMonitor(ctx context.Context, activemonitorname string) (GetActivePlaylistByMonitorRow, error) {
	row := q.db.QueryRowContext(ctx, getActivePlaylistByMonitor, activemonitorname)
	var i GetActivePlaylistByMonitorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Interval,
		&i.Showanimations,
		&i.Alwaysstartonfirstimage,
		&i.Order,
		&i.Currentimageindex,
		&i.Activemonitor,
		&i.Activemonitorname,
	)
	return i, err
}

const getActivePlaylists = `-- name: GetActivePlaylists :many
SELECT p.id, p.name, p.type, p.interval, p.showAnimations, p.alwaysStartOnFirstImage, p."order", p.currentImageIndex,
       ap.activeMonitor, ap.activeMonitorName
FROM Playlists p
INNER JOIN activePlaylists ap ON p.id = ap.playlistID
`

type GetActivePlaylistsRow struct {
	ID                      int64          `json:"id"`
	Name                    string         `json:"name"`
	Type                    string         `json:"type"`
	Interval                sql.NullInt64  `json:"interval"`
	Showanimations          int64          `json:"showanimations"`
	Alwaysstartonfirstimage int64          `json:"alwaysstartonfirstimage"`
	Order                   sql.NullString `json:"order"`
	Currentimageindex       int64          `json:"currentimageindex"`
	Activemonitor           string         `json:"activemonitor"`
	Activemonitorname       string         `json:"activemonitorname"`
}

// Active Playlists Operations
func (q *Queries) GetActivePlaylists(ctx context.Context) ([]GetActivePlaylistsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivePlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActivePlaylistsRow{}
	for rows.Next() {
		var i GetActivePlaylistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Showanimations,
			&i.Alwaysstartonfirstimage,
			&i.Order,
			&i.Currentimageindex,
			&i.Activemonitor,
			&i.Activemonitorname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllImages = `-- name: GetAllImages :many
SELECT id, name, ischecked, isselected, width, height, format
FROM Images
ORDER BY id DESC
`

// Image Operations
func (q *Queries) GetAllImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getAllImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ischecked,
			&i.Isselected,
			&i.Width,
			&i.Height,
			&i.Format,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPlaylists = `-- name: GetAllPlaylists :many
SELECT id, name, type, interval, showAnimations, alwaysStartOnFirstImage, "order", currentImageIndex
FROM Playlists
ORDER BY name ASC
`

// Additional Playlist Operations
func (q *Queries) GetAllPlaylists(ctx context.Context) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Showanimations,
			&i.Alwaysstartonfirstimage,
			&i.Order,
			&i.Currentimageindex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppConfig = `-- name: GetAppConfig :one
SELECT config FROM appConfig LIMIT 1
`

// Configuration Operations
func (q *Queries) GetAppConfig(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppConfig)
	var config string
	err := row.Scan(&config)
	return config, err
}

const getConfigurationExists = `-- name: GetConfigurationExists :one
SELECT COUNT(*) as count FROM appConfig
`

// Enhanced Configuration Operations
func (q *Queries) GetConfigurationExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getConfigurationExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDatabaseInfo = `-- name: GetDatabaseInfo :one
SELECT 
    (SELECT COUNT(*) FROM Images) as image_count,
    (SELECT COUNT(*) FROM Playlists) as playlist_count,
    (SELECT COUNT(*) FROM activePlaylists) as active_playlist_count,
    (SELECT COUNT(*) FROM imageHistory) as history_count
`

type GetDatabaseInfoRow struct {
	ImageCount          int64 `json:"image_count"`
	PlaylistCount       int64 `json:"playlist_count"`
	ActivePlaylistCount int64 `json:"active_playlist_count"`
	HistoryCount        int64 `json:"history_count"`
}

func (q *Queries) GetDatabaseInfo(ctx context.Context) (GetDatabaseInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getDatabaseInfo)
	var i GetDatabaseInfoRow
	err := row.Scan(
		&i.ImageCount,
		&i.PlaylistCount,
		&i.ActivePlaylistCount,
		&i.HistoryCount,
	)
	return i, err
}

const getImage = `-- name: GetImage :one
SELECT id, name, ischecked, isselected, width, height, format FROM Images
WHERE id = ?
`

func (q *Queries) GetImage(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ischecked,
		&i.Isselected,
		&i.Width,
		&i.Height,
		&i.Format,
	)
	return i, err
}

const getImageByName = `-- name: GetImageByName :one
SELECT id, name, ischecked, isselected, width, height, format
FROM Images
WHERE name = ?
`

func (q *Queries) GetImageByName(ctx context.Context, name string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByName, name)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ischecked,
		&i.Isselected,
		&i.Width,
		&i.Height,
		&i.Format,
	)
	return i, err
}

const getImageFormatStats = `-- name: GetImageFormatStats :many
SELECT format, COUNT(*) as count
FROM Images
GROUP BY format
ORDER BY count DESC
`

type GetImageFormatStatsRow struct {
	Format string `json:"format"`
	Count  int64  `json:"count"`
}

// Statistics and Analytics
func (q *Queries) GetImageFormatStats(ctx context.Context) ([]GetImageFormatStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getImageFormatStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImageFormatStatsRow{}
	for rows.Next() {
		var i GetImageFormatStatsRow
		if err := rows.Scan(&i.Format, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageHistory = `-- name: GetImageHistory :many
SELECT i.id, i.name, i.width, i.height, i.isChecked, i.isSelected, i.format, ih.monitor, ih.time
FROM imageHistory ih
INNER JOIN Images i ON ih.imageID = i.id
ORDER BY ih.time DESC
LIMIT ?
`

type GetImageHistoryRow struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Width      int64          `json:"width"`
	Height     int64          `json:"height"`
	Ischecked  int64          `json:"ischecked"`
	Isselected int64          `json:"isselected"`
	Format     string         `json:"format"`
	Monitor    string         `json:"monitor"`
	Time       sql.NullString `json:"time"`
}

// Image History Operations
func (q *Queries) GetImageHistory(ctx context.Context, limit int64) ([]GetImageHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getImageHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImageHistoryRow{}
	for rows.Next() {
		var i GetImageHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.Ischecked,
			&i.Isselected,
			&i.Format,
			&i.Monitor,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageHistoryByMonitor = `-- name: GetImageHistoryByMonitor :many
SELECT i.id, i.name, i.width, i.height, i.isChecked, i.isSelected, i.format, ih.monitor, ih.time
FROM imageHistory ih
INNER JOIN Images i ON ih.imageID = i.id
WHERE ih.monitor = ?
ORDER BY ih.time DESC
LIMIT ?
`

type GetImageHistoryByMonitorParams struct {
	Monitor string `json:"monitor"`
	Limit   int64  `json:"limit"`
}

type GetImageHistoryByMonitorRow struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Width      int64          `json:"width"`
	Height     int64          `json:"height"`
	Ischecked  int64          `json:"ischecked"`
	Isselected int64          `json:"isselected"`
	Format     string         `json:"format"`
	Monitor    string         `json:"monitor"`
	Time       sql.NullString `json:"time"`
}

// Enhanced Image History Operations
func (q *Queries) GetImageHistoryByMonitor(ctx context.Context, arg GetImageHistoryByMonitorParams) ([]GetImageHistoryByMonitorRow, error) {
	rows, err := q.db.QueryContext(ctx, getImageHistoryByMonitor, arg.Monitor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImageHistoryByMonitorRow{}
	for rows.Next() {
		var i GetImageHistoryByMonitorRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.Ischecked,
			&i.Isselected,
			&i.Format,
			&i.Monitor,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageHistoryCount = `-- name: GetImageHistoryCount :one
SELECT COUNT(*) as count
FROM imageHistory
`

func (q *Queries) GetImageHistoryCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getImageHistoryCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getImageHistoryPaginated = `-- name: GetImageHistoryPaginated :many
SELECT i.id, i.name, i.width, i.height, i.isChecked, i.isSelected, i.format, ih.monitor, ih.time
FROM imageHistory ih
INNER JOIN Images i ON ih.imageID = i.id
ORDER BY ih.time DESC
LIMIT ? OFFSET ?
`

type GetImageHistoryPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GetImageHistoryPaginatedRow struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Width      int64          `json:"width"`
	Height     int64          `json:"height"`
	Ischecked  int64          `json:"ischecked"`
	Isselected int64          `json:"isselected"`
	Format     string         `json:"format"`
	Monitor    string         `json:"monitor"`
	Time       sql.NullString `json:"time"`
}

func (q *Queries) GetImageHistoryPaginated(ctx context.Context, arg GetImageHistoryPaginatedParams) ([]GetImageHistoryPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getImageHistoryPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImageHistoryPaginatedRow{}
	for rows.Next() {
		var i GetImageHistoryPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.Ischecked,
			&i.Isselected,
			&i.Format,
			&i.Monitor,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesByDimensions = `-- name: GetImagesByDimensions :many
SELECT id, name, isChecked, isSelected, width, height, format
FROM Images
WHERE width >= ? AND height >= ?
ORDER BY width DESC, height DESC
`

type GetImagesByDimensionsParams struct {
	Width  int64 `json:"width"`
	Height int64 `json:"height"`
}

func (q *Queries) GetImagesByDimensions(ctx context.Context, arg GetImagesByDimensionsParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getImagesByDimensions, arg.Width, arg.Height)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ischecked,
			&i.Isselected,
			&i.Width,
			&i.Height,
			&i.Format,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesByFormat = `-- name: GetImagesByFormat :many
SELECT id, name, isChecked, isSelected, width, height, format
FROM Images
WHERE format = ?
ORDER BY name ASC
`

func (q *Queries) GetImagesByFormat(ctx context.Context, format string) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getImagesByFormat, format)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ischecked,
			&i.Isselected,
			&i.Width,
			&i.Height,
			&i.Format,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxPlaylistImageIndex = `-- name: GetMaxPlaylistImageIndex :one
SELECT COALESCE(MAX(indexInPlaylist), -1) as max_index
FROM imagesInPlaylist
WHERE playlistID = ?
`

func (q *Queries) GetMaxPlaylistImageIndex(ctx context.Context, playlistid int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxPlaylistImageIndex, playlistid)
	var max_index interface{}
	err := row.Scan(&max_index)
	return max_index, err
}

const getMostUsedImages = `-- name: GetMostUsedImages :many
SELECT i.id, i.name, i.width, i.height, i.format, COUNT(ih.imageID) as usage_count
FROM Images i
LEFT JOIN imageHistory ih ON i.id = ih.imageID
GROUP BY i.id, i.name, i.width, i.height, i.format
ORDER BY usage_count DESC
LIMIT ?
`

type GetMostUsedImagesRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Width      int64  `json:"width"`
	Height     int64  `json:"height"`
	Format     string `json:"format"`
	UsageCount int64  `json:"usage_count"`
}

func (q *Queries) GetMostUsedImages(ctx context.Context, limit int64) ([]GetMostUsedImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMostUsedImages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMostUsedImagesRow{}
	for rows.Next() {
		var i GetMostUsedImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.Format,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, name, type, interval, showAnimations, alwaysStartOnFirstImage, "order", currentImageIndex
FROM Playlists
WHERE id = ?
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id int64) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistByID, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Interval,
		&i.Showanimations,
		&i.Alwaysstartonfirstimage,
		&i.Order,
		&i.Currentimageindex,
	)
	return i, err
}

const getPlaylistByName = `-- name: GetPlaylistByName :one
SELECT id, name, type, interval, showAnimations, alwaysStartOnFirstImage, "order", currentImageIndex
FROM Playlists
WHERE name = ?
`

// Playlist Operations
func (q *Queries) GetPlaylistByName(ctx context.Context, name string) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistByName, name)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Interval,
		&i.Showanimations,
		&i.Alwaysstartonfirstimage,
		&i.Order,
		&i.Currentimageindex,
	)
	return i, err
}

const getPlaylistImageCount = `-- name: GetPlaylistImageCount :one
SELECT COUNT(*) as count
FROM imagesInPlaylist
WHERE playlistID = ?
`

// Enhanced Playlist Image Operations
func (q *Queries) GetPlaylistImageCount(ctx context.Context, playlistid int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistImageCount, playlistid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlaylistImagesOrdered = `-- name: GetPlaylistImagesOrdered :many
SELECT i.id, i.name, i.width, i.height, i.ischecked, i.isselected, i.format, ip.time
FROM imagesInPlaylist ip
INNER JOIN Images i ON ip.imageID = i.id
WHERE ip.playlistID = ?
ORDER BY ip.indexInPlaylist ASC
`

type GetPlaylistImagesOrderedRow struct {
	ID         int64         `json:"id"`
	Name       string        `json:"name"`
	Width      int64         `json:"width"`
	Height     int64         `json:"height"`
	Ischecked  int64         `json:"ischecked"`
	Isselected int64         `json:"isselected"`
	Format     string        `json:"format"`
	Time       sql.NullInt64 `json:"time"`
}

// Playlist Images Operations
func (q *Queries) GetPlaylistImagesOrdered(ctx context.Context, playlistid int64) ([]GetPlaylistImagesOrderedRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistImagesOrdered, playlistid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlaylistImagesOrderedRow{}
	for rows.Next() {
		var i GetPlaylistImagesOrderedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.Ischecked,
			&i.Isselected,
			&i.Format,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistImagesRandom = `-- name: GetPlaylistImagesRandom :many
SELECT i.id, i.name, i.width, i.height, i.isChecked, i.isSelected, i.format, ip.time
FROM imagesInPlaylist ip
INNER JOIN Images i ON ip.imageID = i.id
WHERE ip.playlistID = ?
ORDER BY RANDOM()
`

type GetPlaylistImagesRandomRow struct {
	ID         int64         `json:"id"`
	Name       string        `json:"name"`
	Width      int64         `json:"width"`
	Height     int64         `json:"height"`
	Ischecked  int64         `json:"ischecked"`
	Isselected int64         `json:"isselected"`
	Format     string        `json:"format"`
	Time       sql.NullInt64 `json:"time"`
}

func (q *Queries) GetPlaylistImagesRandom(ctx context.Context, playlistid int64) ([]GetPlaylistImagesRandomRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistImagesRandom, playlistid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlaylistImagesRandomRow{}
	for rows.Next() {
		var i GetPlaylistImagesRandomRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.Ischecked,
			&i.Isselected,
			&i.Format,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistImagesWithPagination = `-- name: GetPlaylistImagesWithPagination :many
SELECT i.id, i.name, i.width, i.height, i.isChecked, i.isSelected, i.format, ip.time, ip.indexInPlaylist
FROM imagesInPlaylist ip
INNER JOIN Images i ON ip.imageID = i.id
WHERE ip.playlistID = ?
ORDER BY ip.indexInPlaylist ASC
LIMIT ? OFFSET ?
`

type GetPlaylistImagesWithPaginationParams struct {
	Playlistid int64 `json:"playlistid"`
	Limit      int64 `json:"limit"`
	Offset     int64 `json:"offset"`
}

type GetPlaylistImagesWithPaginationRow struct {
	ID              int64         `json:"id"`
	Name            string        `json:"name"`
	Width           int64         `json:"width"`
	Height          int64         `json:"height"`
	Ischecked       int64         `json:"ischecked"`
	Isselected      int64         `json:"isselected"`
	Format          string        `json:"format"`
	Time            sql.NullInt64 `json:"time"`
	Indexinplaylist int64         `json:"indexinplaylist"`
}

func (q *Queries) GetPlaylistImagesWithPagination(ctx context.Context, arg GetPlaylistImagesWithPaginationParams) ([]GetPlaylistImagesWithPaginationRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistImagesWithPagination, arg.Playlistid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlaylistImagesWithPaginationRow{}
	for rows.Next() {
		var i GetPlaylistImagesWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.Ischecked,
			&i.Isselected,
			&i.Format,
			&i.Time,
			&i.Indexinplaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistTypeStats = `-- name: GetPlaylistTypeStats :many
SELECT type, COUNT(*) as count
FROM Playlists
GROUP BY type
ORDER BY count DESC
`

type GetPlaylistTypeStatsRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

func (q *Queries) GetPlaylistTypeStats(ctx context.Context) ([]GetPlaylistTypeStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistTypeStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlaylistTypeStatsRow{}
	for rows.Next() {
		var i GetPlaylistTypeStatsRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomImages = `-- name: GetRandomImages :many
SELECT id, name, isChecked, isSelected, width, height, format
FROM Images
WHERE name NOT IN (/*SLICE:excludeNames*/?)
ORDER BY RANDOM()
LIMIT ?
`

type GetRandomImagesParams struct {
	ExcludeNames []string `json:"excludeNames"`
	Limit        int64    `json:"limit"`
}

// Random Image Operations
func (q *Queries) GetRandomImages(ctx context.Context, arg GetRandomImagesParams) ([]Image, error) {
	query := getRandomImages
	var queryParams []interface{}
	if len(arg.ExcludeNames) > 0 {
		for _, v := range arg.ExcludeNames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:excludeNames*/?", strings.Repeat(",?", len(arg.ExcludeNames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:excludeNames*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ischecked,
			&i.Isselected,
			&i.Width,
			&i.Height,
			&i.Format,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomImagesAll = `-- name: GetRandomImagesAll :many
SELECT id, name, isChecked, isSelected, width, height, format
FROM Images
ORDER BY RANDOM()
LIMIT ?
`

func (q *Queries) GetRandomImagesAll(ctx context.Context, limit int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getRandomImagesAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ischecked,
			&i.Isselected,
			&i.Width,
			&i.Height,
			&i.Format,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSelectedMonitor = `-- name: GetSelectedMonitor :one
SELECT monitor FROM selectedMonitor LIMIT 1
`

// Selected Monitor Operations
func (q *Queries) GetSelectedMonitor(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSelectedMonitor)
	var monitor string
	err := row.Scan(&monitor)
	return monitor, err
}

const getSwwwConfig = `-- name: GetSwwwConfig :one
SELECT config FROM swwwConfig LIMIT 1
`

func (q *Queries) GetSwwwConfig(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSwwwConfig)
	var config string
	err := row.Scan(&config)
	return config, err
}

const getSwwwConfigExists = `-- name: GetSwwwConfigExists :one
SELECT COUNT(*) as count FROM swwwConfig
`

func (q *Queries) GetSwwwConfigExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSwwwConfigExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertActivePlaylist = `-- name: InsertActivePlaylist :exec
INSERT INTO activePlaylists (playlistID, activeMonitor, activeMonitorName)
VALUES (?, ?, ?)
`

type InsertActivePlaylistParams struct {
	Playlistid        int64  `json:"playlistid"`
	Activemonitor     string `json:"activemonitor"`
	Activemonitorname string `json:"activemonitorname"`
}

func (q *Queries) InsertActivePlaylist(ctx context.Context, arg InsertActivePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, insertActivePlaylist, arg.Playlistid, arg.Activemonitor, arg.Activemonitorname)
	return err
}

const insertImages = `-- name: InsertImages :many
INSERT INTO Images (name, ischecked, isselected, width, height, format)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, ischecked, isselected, width, height, format
`

type InsertImagesParams struct {
	Name       string `json:"name"`
	Ischecked  int64  `json:"ischecked"`
	Isselected int64  `json:"isselected"`
	Width      int64  `json:"width"`
	Height     int64  `json:"height"`
	Format     string `json:"format"`
}

func (q *Queries) InsertImages(ctx context.Context, arg InsertImagesParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, insertImages,
		arg.Name,
		arg.Ischecked,
		arg.Isselected,
		arg.Width,
		arg.Height,
		arg.Format,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ischecked,
			&i.Isselected,
			&i.Width,
			&i.Height,
			&i.Format,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertImagesBatch = `-- name: InsertImagesBatch :exec
INSERT INTO Images (name, isChecked, isSelected, width, height, format)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertImagesBatchParams struct {
	Name       string `json:"name"`
	Ischecked  int64  `json:"ischecked"`
	Isselected int64  `json:"isselected"`
	Width      int64  `json:"width"`
	Height     int64  `json:"height"`
	Format     string `json:"format"`
}

// Batch Image Operations
func (q *Queries) InsertImagesBatch(ctx context.Context, arg InsertImagesBatchParams) error {
	_, err := q.db.ExecContext(ctx, insertImagesBatch,
		arg.Name,
		arg.Ischecked,
		arg.Isselected,
		arg.Width,
		arg.Height,
		arg.Format,
	)
	return err
}

const insertMultiplePlaylistImages = `-- name: InsertMultiplePlaylistImages :exec
INSERT INTO imagesInPlaylist (imageID, playlistID, indexInPlaylist, time)
VALUES (?, ?, ?, ?)
`

type InsertMultiplePlaylistImagesParams struct {
	Imageid         int64         `json:"imageid"`
	Playlistid      int64         `json:"playlistid"`
	Indexinplaylist int64         `json:"indexinplaylist"`
	Time            sql.NullInt64 `json:"time"`
}

func (q *Queries) InsertMultiplePlaylistImages(ctx context.Context, arg InsertMultiplePlaylistImagesParams) error {
	_, err := q.db.ExecContext(ctx, insertMultiplePlaylistImages,
		arg.Imageid,
		arg.Playlistid,
		arg.Indexinplaylist,
		arg.Time,
	)
	return err
}

const insertPlaylistImage = `-- name: InsertPlaylistImage :exec
INSERT INTO imagesInPlaylist (imageID, playlistID, indexInPlaylist, time)
VALUES (?, ?, ?, ?)
`

type InsertPlaylistImageParams struct {
	Imageid         int64         `json:"imageid"`
	Playlistid      int64         `json:"playlistid"`
	Indexinplaylist int64         `json:"indexinplaylist"`
	Time            sql.NullInt64 `json:"time"`
}

func (q *Queries) InsertPlaylistImage(ctx context.Context, arg InsertPlaylistImageParams) error {
	_, err := q.db.ExecContext(ctx, insertPlaylistImage,
		arg.Imageid,
		arg.Playlistid,
		arg.Indexinplaylist,
		arg.Time,
	)
	return err
}

const listImages = `-- name: ListImages :many
SELECT id, name, ischecked, isselected, width, height, format FROM Images
ORDER BY name
`

func (q *Queries) ListImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ischecked,
			&i.Isselected,
			&i.Width,
			&i.Height,
			&i.Format,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeActivePlaylist = `-- name: RemoveActivePlaylist :exec
DELETE FROM activePlaylists
WHERE activeMonitorName = ?
`

func (q *Queries) RemoveActivePlaylist(ctx context.Context, activemonitorname string) error {
	_, err := q.db.ExecContext(ctx, removeActivePlaylist, activemonitorname)
	return err
}

const removeActivePlaylistByID = `-- name: RemoveActivePlaylistByID :exec
DELETE FROM activePlaylists
WHERE playlistID = ?
`

func (q *Queries) RemoveActivePlaylistByID(ctx context.Context, playlistid int64) error {
	_, err := q.db.ExecContext(ctx, removeActivePlaylistByID, playlistid)
	return err
}

const searchImagesByName = `-- name: SearchImagesByName :many
SELECT id, name, isChecked, isSelected, width, height, format
FROM Images
WHERE name LIKE ?
ORDER BY name ASC
LIMIT ?
`

type SearchImagesByNameParams struct {
	Name  string `json:"name"`
	Limit int64  `json:"limit"`
}

// Advanced Search Operations
func (q *Queries) SearchImagesByName(ctx context.Context, arg SearchImagesByNameParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, searchImagesByName, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ischecked,
			&i.Isselected,
			&i.Width,
			&i.Height,
			&i.Format,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSelectedMonitor = `-- name: SetSelectedMonitor :exec
INSERT INTO selectedMonitor (monitor)
VALUES (?)
ON CONFLICT DO UPDATE SET monitor = excluded.monitor
`

func (q *Queries) SetSelectedMonitor(ctx context.Context, monitor string) error {
	_, err := q.db.ExecContext(ctx, setSelectedMonitor, monitor)
	return err
}

const updateImageHistoryTime = `-- name: UpdateImageHistoryTime :exec
UPDATE imageHistory
SET time = strftime('%s', 'now')
WHERE imageID = ? AND monitor = ?
`

type UpdateImageHistoryTimeParams struct {
	Imageid int64  `json:"imageid"`
	Monitor string `json:"monitor"`
}

func (q *Queries) UpdateImageHistoryTime(ctx context.Context, arg UpdateImageHistoryTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateImageHistoryTime, arg.Imageid, arg.Monitor)
	return err
}

const updateImageSelection = `-- name: UpdateImageSelection :exec
UPDATE Images
SET isselected = ?, ischecked = ?
WHERE id = ?
`

type UpdateImageSelectionParams struct {
	Isselected int64 `json:"isselected"`
	Ischecked  int64 `json:"ischecked"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateImageSelection(ctx context.Context, arg UpdateImageSelectionParams) error {
	_, err := q.db.ExecContext(ctx, updateImageSelection, arg.Isselected, arg.Ischecked, arg.ID)
	return err
}

const updateImagesBatch = `-- name: UpdateImagesBatch :exec
UPDATE Images 
SET isSelected = ?, isChecked = ?
WHERE id IN (/*SLICE:imageIDs*/?)
`

type UpdateImagesBatchParams struct {
	Isselected int64   `json:"isselected"`
	Ischecked  int64   `json:"ischecked"`
	ImageIDs   []int64 `json:"imageIDs"`
}

func (q *Queries) UpdateImagesBatch(ctx context.Context, arg UpdateImagesBatchParams) error {
	query := updateImagesBatch
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Isselected)
	queryParams = append(queryParams, arg.Ischecked)
	if len(arg.ImageIDs) > 0 {
		for _, v := range arg.ImageIDs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:imageIDs*/?", strings.Repeat(",?", len(arg.ImageIDs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:imageIDs*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updatePlaylistCurrentIndex = `-- name: UpdatePlaylistCurrentIndex :exec
UPDATE Playlists
SET currentImageIndex = ?
WHERE name = ?
`

type UpdatePlaylistCurrentIndexParams struct {
	Currentimageindex int64  `json:"currentimageindex"`
	Name              string `json:"name"`
}

func (q *Queries) UpdatePlaylistCurrentIndex(ctx context.Context, arg UpdatePlaylistCurrentIndexParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylistCurrentIndex, arg.Currentimageindex, arg.Name)
	return err
}

const updatePlaylistCurrentIndexByID = `-- name: UpdatePlaylistCurrentIndexByID :exec
UPDATE Playlists
SET currentImageIndex = ?
WHERE id = ?
`

type UpdatePlaylistCurrentIndexByIDParams struct {
	Currentimageindex int64 `json:"currentimageindex"`
	ID                int64 `json:"id"`
}

func (q *Queries) UpdatePlaylistCurrentIndexByID(ctx context.Context, arg UpdatePlaylistCurrentIndexByIDParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylistCurrentIndexByID, arg.Currentimageindex, arg.ID)
	return err
}

const updatePlaylistImageOrder = `-- name: UpdatePlaylistImageOrder :exec
UPDATE imagesInPlaylist
SET indexInPlaylist = ?
WHERE playlistID = ? AND imageID = ?
`

type UpdatePlaylistImageOrderParams struct {
	Indexinplaylist int64 `json:"indexinplaylist"`
	Playlistid      int64 `json:"playlistid"`
	Imageid         int64 `json:"imageid"`
}

func (q *Queries) UpdatePlaylistImageOrder(ctx context.Context, arg UpdatePlaylistImageOrderParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylistImageOrder, arg.Indexinplaylist, arg.Playlistid, arg.Imageid)
	return err
}

const upsertAppConfig = `-- name: UpsertAppConfig :exec
INSERT INTO appConfig (config)
VALUES (?)
ON CONFLICT DO UPDATE SET config = excluded.config
`

func (q *Queries) UpsertAppConfig(ctx context.Context, config string) error {
	_, err := q.db.ExecContext(ctx, upsertAppConfig, config)
	return err
}

const upsertPlaylist = `-- name: UpsertPlaylist :one
INSERT INTO Playlists (name, type, interval, showAnimations, alwaysStartOnFirstImage, "order", currentImageIndex)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    type = excluded.type,
    interval = excluded.interval,
    showAnimations = excluded.showAnimations,
    alwaysStartOnFirstImage = excluded.alwaysStartOnFirstImage,
    "order" = excluded."order",
    currentImageIndex = excluded.currentImageIndex
RETURNING id
`

type UpsertPlaylistParams struct {
	Name                    string         `json:"name"`
	Type                    string         `json:"type"`
	Interval                sql.NullInt64  `json:"interval"`
	Showanimations          int64          `json:"showanimations"`
	Alwaysstartonfirstimage int64          `json:"alwaysstartonfirstimage"`
	Order                   sql.NullString `json:"order"`
	Currentimageindex       int64          `json:"currentimageindex"`
}

func (q *Queries) UpsertPlaylist(ctx context.Context, arg UpsertPlaylistParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertPlaylist,
		arg.Name,
		arg.Type,
		arg.Interval,
		arg.Showanimations,
		arg.Alwaysstartonfirstimage,
		arg.Order,
		arg.Currentimageindex,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSwwwConfig = `-- name: UpsertSwwwConfig :exec
INSERT INTO swwwConfig (config)
VALUES (?)
ON CONFLICT DO UPDATE SET config = excluded.config
`

func (q *Queries) UpsertSwwwConfig(ctx context.Context, config string) error {
	_, err := q.db.ExecContext(ctx, upsertSwwwConfig, config)
	return err
}
