// Package walqtclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package walqtclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Defines values for ImagePresentationRequestImageFitMode.
const (
	ImagePresentationRequestImageFitModeContain   ImagePresentationRequestImageFitMode = "contain"
	ImagePresentationRequestImageFitModeCover     ImagePresentationRequestImageFitMode = "cover"
	ImagePresentationRequestImageFitModeFill      ImagePresentationRequestImageFitMode = "fill"
	ImagePresentationRequestImageFitModeNone      ImagePresentationRequestImageFitMode = "none"
	ImagePresentationRequestImageFitModeScaleDown ImagePresentationRequestImageFitMode = "scale-down"
)

// Defines values for ImagePresentationRequestImageRendering.
const (
	Auto       ImagePresentationRequestImageRendering = "auto"
	CrispEdges ImagePresentationRequestImageRendering = "crisp-edges"
	Pixelated  ImagePresentationRequestImageRendering = "pixelated"
)

// Defines values for LoadRequestKind.
const (
	LoadRequestKindImage LoadRequestKind = "image"
	LoadRequestKindVideo LoadRequestKind = "video"
	LoadRequestKindWeb   LoadRequestKind = "web"
)

// Defines values for LoadRequestTransition.
const (
	LoadRequestTransitionAny         LoadRequestTransition = "any"
	LoadRequestTransitionBlurThrough LoadRequestTransition = "blur_through"
	LoadRequestTransitionBottom      LoadRequestTransition = "bottom"
	LoadRequestTransitionCenter      LoadRequestTransition = "center"
	LoadRequestTransitionFade        LoadRequestTransition = "fade"
	LoadRequestTransitionGrow        LoadRequestTransition = "grow"
	LoadRequestTransitionLeft        LoadRequestTransition = "left"
	LoadRequestTransitionNone        LoadRequestTransition = "none"
	LoadRequestTransitionOuter       LoadRequestTransition = "outer"
	LoadRequestTransitionRandom      LoadRequestTransition = "random"
	LoadRequestTransitionRight       LoadRequestTransition = "right"
	LoadRequestTransitionTop         LoadRequestTransition = "top"
	LoadRequestTransitionWave        LoadRequestTransition = "wave"
	LoadRequestTransitionWipe        LoadRequestTransition = "wipe"
)

// Defines values for MonitorStatusCurrentKind.
const (
	MonitorStatusCurrentKindImage MonitorStatusCurrentKind = "image"
	MonitorStatusCurrentKindVideo MonitorStatusCurrentKind = "video"
	MonitorStatusCurrentKindWeb   MonitorStatusCurrentKind = "web"
)

// Defines values for ParallaxMoveRequestDirection.
const (
	Down  ParallaxMoveRequestDirection = "down"
	Left  ParallaxMoveRequestDirection = "left"
	Right ParallaxMoveRequestDirection = "right"
	Up    ParallaxMoveRequestDirection = "up"
)

// Defines values for WallpaperTargetKind.
const (
	Image WallpaperTargetKind = "image"
	Video WallpaperTargetKind = "video"
	Web   WallpaperTargetKind = "web"
)

// AcceptedResponse defines model for AcceptedResponse.
type AcceptedResponse struct {
	Accepted bool `json:"accepted"`
	Ok       bool `json:"ok"`
}

// AppliedResponse defines model for AppliedResponse.
type AppliedResponse struct {
	// Applied Number of monitor windows the operation was applied to
	Applied int  `json:"applied"`
	Ok      bool `json:"ok"`
}

// CapabilitiesRequest Overrides runtime capabilities for the wallpaper loaded from
// `source_target`. All capability fields are optional; absent fields are
// left unchanged.
type CapabilitiesRequest struct {
	Capabilities *struct {
		// AudioReactive Enable audio capture and dispatch to the wallpaper
		AudioReactive *bool `json:"audio_reactive,omitempty"`

		// Keyboard Allow keyboard input to reach the wallpaper
		Keyboard *bool `json:"keyboard,omitempty"`

		// PointerInteractive Allow mouse/pointer events to reach the wallpaper
		PointerInteractive *bool `json:"pointer_interactive,omitempty"`
	} `json:"capabilities,omitempty"`

	// SourceTarget Absolute path of the wallpaper whose capabilities should be updated
	SourceTarget string `json:"source_target"`
}

// Error defines model for Error.
type Error struct {
	// Error Human-readable error message
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	ApiVersion string `json:"api_version"`
	Ok         bool   `json:"ok"`
	Service    string `json:"service"`
}

// ImagePresentationRequest Sets image scaling and rendering quality globally across all monitors.
type ImagePresentationRequest struct {
	// ImageFitMode CSS `object-fit` style value; defaults to `cover` when absent
	ImageFitMode *ImagePresentationRequestImageFitMode `json:"image_fit_mode,omitempty"`

	// ImageRendering CSS `image-rendering` style value; defaults to `auto` when absent
	ImageRendering *ImagePresentationRequestImageRendering `json:"image_rendering,omitempty"`
}

// ImagePresentationRequestImageFitMode CSS `object-fit` style value; defaults to `cover` when absent
type ImagePresentationRequestImageFitMode string

// ImagePresentationRequestImageRendering CSS `image-rendering` style value; defaults to `auto` when absent
type ImagePresentationRequestImageRendering string

// LoadParallax Initial parallax state applied at load time. Separate from the
// `/wallpaper/parallax` route which updates state on a running wallpaper.
type LoadParallax struct {
	AnimationMs *int       `json:"animation_ms,omitempty"`
	Easing      *[]float32 `json:"easing,omitempty"`
	Enabled     *bool      `json:"enabled,omitempty"`
	ResetMs     *int       `json:"reset_ms,omitempty"`
	StepPercent *float32   `json:"step_percent,omitempty"`
	Zoom        *float64   `json:"zoom,omitempty"`
}

// LoadRequest Loads a wallpaper. When `targets` is present, each entry names a monitor
// and provides its own `target` path (and optional `kind`). When `targets`
// is absent the top-level `target` and `kind` apply to all monitors.
type LoadRequest struct {
	// AudioEnabled Whether audio reactivity is enabled for this wallpaper
	AudioEnabled *bool `json:"audio_enabled,omitempty"`

	// DurationMs Transition duration in milliseconds (forwarded to the renderer)
	DurationMs *int `json:"duration_ms,omitempty"`

	// ImageFitMode How the image fits the monitor (e.g. `cover`, `contain`, `fill`). Only meaningful for `kind: image`.
	ImageFitMode *string `json:"image_fit_mode,omitempty"`

	// ImageRendering CSS `image-rendering` hint (e.g. `auto`, `pixelated`, `crisp-edges`). Only meaningful for `kind: image`.
	ImageRendering *string `json:"image_rendering,omitempty"`

	// Kind Wallpaper kind for the fallback `target`
	Kind *LoadRequestKind `json:"kind,omitempty"`

	// Parallax Initial parallax state applied at load time. Separate from the
	// `/wallpaper/parallax` route which updates state on a running wallpaper.
	Parallax *LoadParallax `json:"parallax,omitempty"`

	// Target Fallback path used when `targets` is absent or for monitors not listed in `targets`
	Target *string `json:"target,omitempty"`

	// Targets Per-monitor wallpaper assignments. Omit to target all monitors using the top-level `target`/`kind`.
	Targets *[]WallpaperTarget `json:"targets,omitempty"`

	// Transition Transition effect to use when switching wallpapers. Forwarded to the
	// renderer verbatim; unknown values fall back to `fade`.
	Transition *LoadRequestTransition `json:"transition,omitempty"`

	// TransitionParams Per-effect transition tuning. All fields optional; the renderer applies defaults when omitted.
	TransitionParams *LoadTransitionParams `json:"transition_params,omitempty"`

	// WaitForCompletion When `true`, the request blocks until the renderer acknowledges the transition (or 30 s elapses)
	WaitForCompletion *bool `json:"wait_for_completion,omitempty"`

	// WallpaperConfigValues Arbitrary key/value config object injected into the web wallpaper as
	// `window.__WAYPAPER_CONFIG` and dispatched as the `waypaper:config` event.
	// Only meaningful for `kind: web`.
	WallpaperConfigValues *map[string]interface{} `json:"wallpaper_config_values,omitempty"`
}

// LoadRequestKind Wallpaper kind for the fallback `target`
type LoadRequestKind string

// LoadRequestTransition Transition effect to use when switching wallpapers. Forwarded to the
// renderer verbatim; unknown values fall back to `fade`.
type LoadRequestTransition string

// LoadTransitionParams Per-effect transition tuning. All fields optional; the renderer applies defaults when omitted.
type LoadTransitionParams struct {
	AngleDeg *float64 `json:"angle_deg,omitempty"`

	// Bezier Cubic-bezier control points [x1, y1, x2, y2]
	Bezier         *[]float32 `json:"bezier,omitempty"`
	OriginXPercent *float32   `json:"origin_x_percent,omitempty"`
	OriginYPercent *float32   `json:"origin_y_percent,omitempty"`

	// Seed Per-request randomness seed for `random`/`any` transitions
	Seed                 *int     `json:"seed,omitempty"`
	WaveAmplitudePercent *float32 `json:"wave_amplitude_percent,omitempty"`
	WaveFrequency        *float32 `json:"wave_frequency,omitempty"`
}

// MonitorGeometry defines model for MonitorGeometry.
type MonitorGeometry struct {
	Height int `json:"height"`

	// Name Wayland output name (e.g. "DP-1")
	Name  string `json:"name"`
	Width int    `json:"width"`
	X     int    `json:"x"`
	Y     int    `json:"y"`
}

// MonitorStatus defines model for MonitorStatus.
type MonitorStatus struct {
	CurrentKind MonitorStatusCurrentKind `json:"current_kind"`

	// CurrentTarget Absolute path or URI of the active wallpaper (absent when no wallpaper has been loaded)
	CurrentTarget  *string       `json:"current_target,omitempty"`
	InProgress     bool          `json:"in_progress"`
	LastTransition string        `json:"last_transition"`
	Name           string        `json:"name"`
	Parallax       ParallaxState `json:"parallax"`
	Visible        bool          `json:"visible"`
}

// MonitorStatusCurrentKind defines model for MonitorStatus.CurrentKind.
type MonitorStatusCurrentKind string

// NetworkSettingsRequest Enables or disables global network access for all wallpapers.
// Accepts `allow_network_wallpapers` (preferred) or the legacy alias
// `enabled`. When both are present, `allow_network_wallpapers` takes
// precedence.
type NetworkSettingsRequest struct {
	// AllowNetworkWallpapers Preferred field name
	AllowNetworkWallpapers *bool `json:"allow_network_wallpapers,omitempty"`

	// Enabled Legacy alias for `allow_network_wallpapers`
	Enabled *bool `json:"enabled,omitempty"`
}

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok bool `json:"ok"`
}

// ParallaxMoveRequest Nudges the parallax offset one step in the given direction.
type ParallaxMoveRequest struct {
	Direction ParallaxMoveRequestDirection `json:"direction"`

	// Name Target a single monitor by Wayland output name (omit for all)
	Name *string `json:"name,omitempty"`

	// Targets Alternative to `name`
	Targets *[]WallpaperTarget `json:"targets,omitempty"`
}

// ParallaxMoveRequestDirection defines model for ParallaxMoveRequest.Direction.
type ParallaxMoveRequestDirection string

// ParallaxRequest Sets parallax parameters for one or all monitors. Use `name` (single
// monitor) or `targets` (list of monitors) to narrow the target set.
// Omit both to apply to all monitors.
type ParallaxRequest struct {
	AnimationMs *int `json:"animation_ms,omitempty"`

	// Easing Cubic-bezier control points [x1, y1, x2, y2]
	Easing  *[]float64 `json:"easing,omitempty"`
	Enabled *bool      `json:"enabled,omitempty"`

	// Name Target a single monitor by Wayland output name
	Name        *string  `json:"name,omitempty"`
	ResetMs     *int     `json:"reset_ms,omitempty"`
	StepPercent *float64 `json:"step_percent,omitempty"`

	// Targets Alternative to `name` — list of monitor names to target
	Targets *[]WallpaperTarget `json:"targets,omitempty"`
	Zoom    *float64           `json:"zoom,omitempty"`
}

// ParallaxState defines model for ParallaxState.
type ParallaxState struct {
	AnimationMs int `json:"animation_ms"`

	// Easing Cubic-bezier control points [x1, y1, x2, y2]
	Easing      []float64 `json:"easing"`
	Enabled     bool      `json:"enabled"`
	OffsetX     float64   `json:"offset_x"`
	OffsetY     float64   `json:"offset_y"`
	ResetMs     int       `json:"reset_ms"`
	StepPercent float64   `json:"step_percent"`
	Zoom        float64   `json:"zoom"`
}

// PlaybackRequest Sets the playback policy for the wallpaper loaded from `source_target`.
// The full request body is forwarded verbatim to the renderer via the
// WebChannel bridge, so additional keys beyond `source_target` are
// renderer-defined.
type PlaybackRequest struct {
	// SourceTarget Absolute path of the wallpaper whose playback policy should be updated
	SourceTarget         string                 `json:"source_target"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SchedulerStatus defines model for SchedulerStatus.
type SchedulerStatus struct {
	MaxQueueSize   int    `json:"max_queue_size"`
	Mode           string `json:"mode"`
	QueuedRequests int    `json:"queued_requests"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	ApiVersion string          `json:"api_version"`
	Ok         bool            `json:"ok"`
	Status     WallpaperStatus `json:"status"`
}

// WallpaperConfigRequest Sends configuration values to the wallpaper currently loaded from
// `source_target`. The controller resolves the target monitor(s) by
// matching their `current_target` path against `source_target`.
type WallpaperConfigRequest struct {
	// SourceTarget Absolute path of the wallpaper whose config should be updated
	SourceTarget string `json:"source_target"`

	// Values Arbitrary key/value pairs forwarded to the wallpaper renderer
	Values *map[string]interface{} `json:"values,omitempty"`
}

// WallpaperStatus defines model for WallpaperStatus.
type WallpaperStatus struct {
	MonitorCount   int               `json:"monitor_count"`
	Monitors       []MonitorStatus   `json:"monitors"`
	Scheduler      SchedulerStatus   `json:"scheduler"`
	Topology       []MonitorGeometry `json:"topology"`
	TopologyPolicy string            `json:"topology_policy"`
}

// WallpaperTarget Identifies a single monitor by name and the wallpaper path to load on it
type WallpaperTarget struct {
	// Kind Wallpaper kind; inferred from extension when absent
	Kind *WallpaperTargetKind `json:"kind,omitempty"`

	// Name Wayland output name (must match a connected screen)
	Name string `json:"name"`

	// Target Absolute path to the wallpaper file or web package directory
	Target string `json:"target"`
}

// WallpaperTargetKind Wallpaper kind; inferred from extension when absent
type WallpaperTargetKind string

// SetImagePresentationJSONRequestBody defines body for SetImagePresentation for application/json ContentType.
type SetImagePresentationJSONRequestBody = ImagePresentationRequest

// SetNetworkSettingsJSONRequestBody defines body for SetNetworkSettings for application/json ContentType.
type SetNetworkSettingsJSONRequestBody = NetworkSettingsRequest

// PushCapabilitiesJSONRequestBody defines body for PushCapabilities for application/json ContentType.
type PushCapabilitiesJSONRequestBody = CapabilitiesRequest

// PushWallpaperConfigJSONRequestBody defines body for PushWallpaperConfig for application/json ContentType.
type PushWallpaperConfigJSONRequestBody = WallpaperConfigRequest

// LoadWallpaperJSONRequestBody defines body for LoadWallpaper for application/json ContentType.
type LoadWallpaperJSONRequestBody = LoadRequest

// SetParallaxJSONRequestBody defines body for SetParallax for application/json ContentType.
type SetParallaxJSONRequestBody = ParallaxRequest

// MoveParallaxJSONRequestBody defines body for MoveParallax for application/json ContentType.
type MoveParallaxJSONRequestBody = ParallaxMoveRequest

// SetPlaybackPolicyJSONRequestBody defines body for SetPlaybackPolicy for application/json ContentType.
type SetPlaybackPolicyJSONRequestBody = PlaybackRequest

// PushWallpaperConfigLegacyJSONRequestBody defines body for PushWallpaperConfigLegacy for application/json ContentType.
type PushWallpaperConfigLegacyJSONRequestBody = WallpaperConfigRequest

// PushCapabilitiesLegacyJSONRequestBody defines body for PushCapabilitiesLegacy for application/json ContentType.
type PushCapabilitiesLegacyJSONRequestBody = CapabilitiesRequest

// Getter for additional properties for PlaybackRequest. Returns the specified
// element and whether it was found
func (a PlaybackRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PlaybackRequest
func (a *PlaybackRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PlaybackRequest to handle AdditionalProperties
func (a *PlaybackRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["source_target"]; found {
		err = json.Unmarshal(raw, &a.SourceTarget)
		if err != nil {
			return fmt.Errorf("error reading 'source_target': %w", err)
		}
		delete(object, "source_target")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PlaybackRequest to handle AdditionalProperties
func (a PlaybackRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["source_target"], err = json.Marshal(a.SourceTarget)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'source_target': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetImagePresentationWithBody request with any body
	SetImagePresentationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetImagePresentation(ctx context.Context, body SetImagePresentationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetNetworkSettingsWithBody request with any body
	SetNetworkSettingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetNetworkSettings(ctx context.Context, body SetNetworkSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushCapabilitiesWithBody request with any body
	PushCapabilitiesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PushCapabilities(ctx context.Context, body PushCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushWallpaperConfigWithBody request with any body
	PushWallpaperConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PushWallpaperConfig(ctx context.Context, body PushWallpaperConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LoadWallpaperWithBody request with any body
	LoadWallpaperWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LoadWallpaper(ctx context.Context, body LoadWallpaperJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetParallaxWithBody request with any body
	SetParallaxWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetParallax(ctx context.Context, body SetParallaxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MoveParallaxWithBody request with any body
	MoveParallaxWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	MoveParallax(ctx context.Context, body MoveParallaxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetPlaybackPolicyWithBody request with any body
	SetPlaybackPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetPlaybackPolicy(ctx context.Context, body SetPlaybackPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWallpaperStatus request
	GetWallpaperStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushWallpaperConfigLegacyWithBody request with any body
	PushWallpaperConfigLegacyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PushWallpaperConfigLegacy(ctx context.Context, body PushWallpaperConfigLegacyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushCapabilitiesLegacyWithBody request with any body
	PushCapabilitiesLegacyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PushCapabilitiesLegacy(ctx context.Context, body PushCapabilitiesLegacyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetImagePresentationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetImagePresentationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetImagePresentation(ctx context.Context, body SetImagePresentationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetImagePresentationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetNetworkSettingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetNetworkSettingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetNetworkSettings(ctx context.Context, body SetNetworkSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetNetworkSettingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushCapabilitiesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushCapabilitiesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushCapabilities(ctx context.Context, body PushCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushCapabilitiesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushWallpaperConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushWallpaperConfigRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushWallpaperConfig(ctx context.Context, body PushWallpaperConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushWallpaperConfigRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LoadWallpaperWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoadWallpaperRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LoadWallpaper(ctx context.Context, body LoadWallpaperJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoadWallpaperRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetParallaxWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetParallaxRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetParallax(ctx context.Context, body SetParallaxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetParallaxRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MoveParallaxWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMoveParallaxRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MoveParallax(ctx context.Context, body MoveParallaxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMoveParallaxRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetPlaybackPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetPlaybackPolicyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetPlaybackPolicy(ctx context.Context, body SetPlaybackPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetPlaybackPolicyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWallpaperStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWallpaperStatusRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushWallpaperConfigLegacyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushWallpaperConfigLegacyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushWallpaperConfigLegacy(ctx context.Context, body PushWallpaperConfigLegacyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushWallpaperConfigLegacyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushCapabilitiesLegacyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushCapabilitiesLegacyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushCapabilitiesLegacy(ctx context.Context, body PushCapabilitiesLegacyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushCapabilitiesLegacyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSetImagePresentationRequest calls the generic SetImagePresentation builder with application/json body
func NewSetImagePresentationRequest(server string, body SetImagePresentationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetImagePresentationRequestWithBody(server, "application/json", bodyReader)
}

// NewSetImagePresentationRequestWithBody generates requests for SetImagePresentation with any type of body
func NewSetImagePresentationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/settings/image-presentation")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSetNetworkSettingsRequest calls the generic SetNetworkSettings builder with application/json body
func NewSetNetworkSettingsRequest(server string, body SetNetworkSettingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetNetworkSettingsRequestWithBody(server, "application/json", bodyReader)
}

// NewSetNetworkSettingsRequestWithBody generates requests for SetNetworkSettings with any type of body
func NewSetNetworkSettingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/settings/network")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPushCapabilitiesRequest calls the generic PushCapabilities builder with application/json body
func NewPushCapabilitiesRequest(server string, body PushCapabilitiesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPushCapabilitiesRequestWithBody(server, "application/json", bodyReader)
}

// NewPushCapabilitiesRequestWithBody generates requests for PushCapabilities with any type of body
func NewPushCapabilitiesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wallpaper/capabilities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPushWallpaperConfigRequest calls the generic PushWallpaperConfig builder with application/json body
func NewPushWallpaperConfigRequest(server string, body PushWallpaperConfigJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPushWallpaperConfigRequestWithBody(server, "application/json", bodyReader)
}

// NewPushWallpaperConfigRequestWithBody generates requests for PushWallpaperConfig with any type of body
func NewPushWallpaperConfigRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wallpaper/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewLoadWallpaperRequest calls the generic LoadWallpaper builder with application/json body
func NewLoadWallpaperRequest(server string, body LoadWallpaperJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLoadWallpaperRequestWithBody(server, "application/json", bodyReader)
}

// NewLoadWallpaperRequestWithBody generates requests for LoadWallpaper with any type of body
func NewLoadWallpaperRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wallpaper/load")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSetParallaxRequest calls the generic SetParallax builder with application/json body
func NewSetParallaxRequest(server string, body SetParallaxJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetParallaxRequestWithBody(server, "application/json", bodyReader)
}

// NewSetParallaxRequestWithBody generates requests for SetParallax with any type of body
func NewSetParallaxRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wallpaper/parallax")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMoveParallaxRequest calls the generic MoveParallax builder with application/json body
func NewMoveParallaxRequest(server string, body MoveParallaxJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMoveParallaxRequestWithBody(server, "application/json", bodyReader)
}

// NewMoveParallaxRequestWithBody generates requests for MoveParallax with any type of body
func NewMoveParallaxRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wallpaper/parallax-move")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSetPlaybackPolicyRequest calls the generic SetPlaybackPolicy builder with application/json body
func NewSetPlaybackPolicyRequest(server string, body SetPlaybackPolicyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetPlaybackPolicyRequestWithBody(server, "application/json", bodyReader)
}

// NewSetPlaybackPolicyRequestWithBody generates requests for SetPlaybackPolicy with any type of body
func NewSetPlaybackPolicyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wallpaper/playback")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetWallpaperStatusRequest generates requests for GetWallpaperStatus
func NewGetWallpaperStatusRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wallpaper/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPushWallpaperConfigLegacyRequest calls the generic PushWallpaperConfigLegacy builder with application/json body
func NewPushWallpaperConfigLegacyRequest(server string, body PushWallpaperConfigLegacyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPushWallpaperConfigLegacyRequestWithBody(server, "application/json", bodyReader)
}

// NewPushWallpaperConfigLegacyRequestWithBody generates requests for PushWallpaperConfigLegacy with any type of body
func NewPushWallpaperConfigLegacyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wallpaper/wallpaper-config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPushCapabilitiesLegacyRequest calls the generic PushCapabilitiesLegacy builder with application/json body
func NewPushCapabilitiesLegacyRequest(server string, body PushCapabilitiesLegacyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPushCapabilitiesLegacyRequestWithBody(server, "application/json", bodyReader)
}

// NewPushCapabilitiesLegacyRequestWithBody generates requests for PushCapabilitiesLegacy with any type of body
func NewPushCapabilitiesLegacyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wallpaper/web-capabilities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// SetImagePresentationWithBodyWithResponse request with any body
	SetImagePresentationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetImagePresentationResponse, error)

	SetImagePresentationWithResponse(ctx context.Context, body SetImagePresentationJSONRequestBody, reqEditors ...RequestEditorFn) (*SetImagePresentationResponse, error)

	// SetNetworkSettingsWithBodyWithResponse request with any body
	SetNetworkSettingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetNetworkSettingsResponse, error)

	SetNetworkSettingsWithResponse(ctx context.Context, body SetNetworkSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*SetNetworkSettingsResponse, error)

	// PushCapabilitiesWithBodyWithResponse request with any body
	PushCapabilitiesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushCapabilitiesResponse, error)

	PushCapabilitiesWithResponse(ctx context.Context, body PushCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PushCapabilitiesResponse, error)

	// PushWallpaperConfigWithBodyWithResponse request with any body
	PushWallpaperConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushWallpaperConfigResponse, error)

	PushWallpaperConfigWithResponse(ctx context.Context, body PushWallpaperConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*PushWallpaperConfigResponse, error)

	// LoadWallpaperWithBodyWithResponse request with any body
	LoadWallpaperWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoadWallpaperResponse, error)

	LoadWallpaperWithResponse(ctx context.Context, body LoadWallpaperJSONRequestBody, reqEditors ...RequestEditorFn) (*LoadWallpaperResponse, error)

	// SetParallaxWithBodyWithResponse request with any body
	SetParallaxWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetParallaxResponse, error)

	SetParallaxWithResponse(ctx context.Context, body SetParallaxJSONRequestBody, reqEditors ...RequestEditorFn) (*SetParallaxResponse, error)

	// MoveParallaxWithBodyWithResponse request with any body
	MoveParallaxWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MoveParallaxResponse, error)

	MoveParallaxWithResponse(ctx context.Context, body MoveParallaxJSONRequestBody, reqEditors ...RequestEditorFn) (*MoveParallaxResponse, error)

	// SetPlaybackPolicyWithBodyWithResponse request with any body
	SetPlaybackPolicyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetPlaybackPolicyResponse, error)

	SetPlaybackPolicyWithResponse(ctx context.Context, body SetPlaybackPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*SetPlaybackPolicyResponse, error)

	// GetWallpaperStatusWithResponse request
	GetWallpaperStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWallpaperStatusResponse, error)

	// PushWallpaperConfigLegacyWithBodyWithResponse request with any body
	PushWallpaperConfigLegacyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushWallpaperConfigLegacyResponse, error)

	PushWallpaperConfigLegacyWithResponse(ctx context.Context, body PushWallpaperConfigLegacyJSONRequestBody, reqEditors ...RequestEditorFn) (*PushWallpaperConfigLegacyResponse, error)

	// PushCapabilitiesLegacyWithBodyWithResponse request with any body
	PushCapabilitiesLegacyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushCapabilitiesLegacyResponse, error)

	PushCapabilitiesLegacyWithResponse(ctx context.Context, body PushCapabilitiesLegacyJSONRequestBody, reqEditors ...RequestEditorFn) (*PushCapabilitiesLegacyResponse, error)
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetImagePresentationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OkResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r SetImagePresentationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetImagePresentationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetNetworkSettingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OkResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r SetNetworkSettingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetNetworkSettingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PushCapabilitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AppliedResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r PushCapabilitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushCapabilitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PushWallpaperConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AppliedResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r PushWallpaperConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushWallpaperConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LoadWallpaperResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OkResponse
	JSON202      *AcceptedResponse
	JSON400      *Error
	JSON404      *Error
	JSON504      *Error
}

// Status returns HTTPResponse.Status
func (r LoadWallpaperResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LoadWallpaperResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetParallaxResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OkResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r SetParallaxResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetParallaxResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type MoveParallaxResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OkResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r MoveParallaxResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MoveParallaxResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetPlaybackPolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AppliedResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r SetPlaybackPolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetPlaybackPolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWallpaperStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StatusResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r GetWallpaperStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWallpaperStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PushWallpaperConfigLegacyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AppliedResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r PushWallpaperConfigLegacyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushWallpaperConfigLegacyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PushCapabilitiesLegacyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AppliedResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r PushCapabilitiesLegacyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushCapabilitiesLegacyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// SetImagePresentationWithBodyWithResponse request with arbitrary body returning *SetImagePresentationResponse
func (c *ClientWithResponses) SetImagePresentationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetImagePresentationResponse, error) {
	rsp, err := c.SetImagePresentationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetImagePresentationResponse(rsp)
}

func (c *ClientWithResponses) SetImagePresentationWithResponse(ctx context.Context, body SetImagePresentationJSONRequestBody, reqEditors ...RequestEditorFn) (*SetImagePresentationResponse, error) {
	rsp, err := c.SetImagePresentation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetImagePresentationResponse(rsp)
}

// SetNetworkSettingsWithBodyWithResponse request with arbitrary body returning *SetNetworkSettingsResponse
func (c *ClientWithResponses) SetNetworkSettingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetNetworkSettingsResponse, error) {
	rsp, err := c.SetNetworkSettingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetNetworkSettingsResponse(rsp)
}

func (c *ClientWithResponses) SetNetworkSettingsWithResponse(ctx context.Context, body SetNetworkSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*SetNetworkSettingsResponse, error) {
	rsp, err := c.SetNetworkSettings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetNetworkSettingsResponse(rsp)
}

// PushCapabilitiesWithBodyWithResponse request with arbitrary body returning *PushCapabilitiesResponse
func (c *ClientWithResponses) PushCapabilitiesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushCapabilitiesResponse, error) {
	rsp, err := c.PushCapabilitiesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushCapabilitiesResponse(rsp)
}

func (c *ClientWithResponses) PushCapabilitiesWithResponse(ctx context.Context, body PushCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PushCapabilitiesResponse, error) {
	rsp, err := c.PushCapabilities(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushCapabilitiesResponse(rsp)
}

// PushWallpaperConfigWithBodyWithResponse request with arbitrary body returning *PushWallpaperConfigResponse
func (c *ClientWithResponses) PushWallpaperConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushWallpaperConfigResponse, error) {
	rsp, err := c.PushWallpaperConfigWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushWallpaperConfigResponse(rsp)
}

func (c *ClientWithResponses) PushWallpaperConfigWithResponse(ctx context.Context, body PushWallpaperConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*PushWallpaperConfigResponse, error) {
	rsp, err := c.PushWallpaperConfig(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushWallpaperConfigResponse(rsp)
}

// LoadWallpaperWithBodyWithResponse request with arbitrary body returning *LoadWallpaperResponse
func (c *ClientWithResponses) LoadWallpaperWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoadWallpaperResponse, error) {
	rsp, err := c.LoadWallpaperWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoadWallpaperResponse(rsp)
}

func (c *ClientWithResponses) LoadWallpaperWithResponse(ctx context.Context, body LoadWallpaperJSONRequestBody, reqEditors ...RequestEditorFn) (*LoadWallpaperResponse, error) {
	rsp, err := c.LoadWallpaper(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoadWallpaperResponse(rsp)
}

// SetParallaxWithBodyWithResponse request with arbitrary body returning *SetParallaxResponse
func (c *ClientWithResponses) SetParallaxWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetParallaxResponse, error) {
	rsp, err := c.SetParallaxWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetParallaxResponse(rsp)
}

func (c *ClientWithResponses) SetParallaxWithResponse(ctx context.Context, body SetParallaxJSONRequestBody, reqEditors ...RequestEditorFn) (*SetParallaxResponse, error) {
	rsp, err := c.SetParallax(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetParallaxResponse(rsp)
}

// MoveParallaxWithBodyWithResponse request with arbitrary body returning *MoveParallaxResponse
func (c *ClientWithResponses) MoveParallaxWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MoveParallaxResponse, error) {
	rsp, err := c.MoveParallaxWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMoveParallaxResponse(rsp)
}

func (c *ClientWithResponses) MoveParallaxWithResponse(ctx context.Context, body MoveParallaxJSONRequestBody, reqEditors ...RequestEditorFn) (*MoveParallaxResponse, error) {
	rsp, err := c.MoveParallax(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMoveParallaxResponse(rsp)
}

// SetPlaybackPolicyWithBodyWithResponse request with arbitrary body returning *SetPlaybackPolicyResponse
func (c *ClientWithResponses) SetPlaybackPolicyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetPlaybackPolicyResponse, error) {
	rsp, err := c.SetPlaybackPolicyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetPlaybackPolicyResponse(rsp)
}

func (c *ClientWithResponses) SetPlaybackPolicyWithResponse(ctx context.Context, body SetPlaybackPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*SetPlaybackPolicyResponse, error) {
	rsp, err := c.SetPlaybackPolicy(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetPlaybackPolicyResponse(rsp)
}

// GetWallpaperStatusWithResponse request returning *GetWallpaperStatusResponse
func (c *ClientWithResponses) GetWallpaperStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWallpaperStatusResponse, error) {
	rsp, err := c.GetWallpaperStatus(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWallpaperStatusResponse(rsp)
}

// PushWallpaperConfigLegacyWithBodyWithResponse request with arbitrary body returning *PushWallpaperConfigLegacyResponse
func (c *ClientWithResponses) PushWallpaperConfigLegacyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushWallpaperConfigLegacyResponse, error) {
	rsp, err := c.PushWallpaperConfigLegacyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushWallpaperConfigLegacyResponse(rsp)
}

func (c *ClientWithResponses) PushWallpaperConfigLegacyWithResponse(ctx context.Context, body PushWallpaperConfigLegacyJSONRequestBody, reqEditors ...RequestEditorFn) (*PushWallpaperConfigLegacyResponse, error) {
	rsp, err := c.PushWallpaperConfigLegacy(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushWallpaperConfigLegacyResponse(rsp)
}

// PushCapabilitiesLegacyWithBodyWithResponse request with arbitrary body returning *PushCapabilitiesLegacyResponse
func (c *ClientWithResponses) PushCapabilitiesLegacyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushCapabilitiesLegacyResponse, error) {
	rsp, err := c.PushCapabilitiesLegacyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushCapabilitiesLegacyResponse(rsp)
}

func (c *ClientWithResponses) PushCapabilitiesLegacyWithResponse(ctx context.Context, body PushCapabilitiesLegacyJSONRequestBody, reqEditors ...RequestEditorFn) (*PushCapabilitiesLegacyResponse, error) {
	rsp, err := c.PushCapabilitiesLegacy(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushCapabilitiesLegacyResponse(rsp)
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseSetImagePresentationResponse parses an HTTP response from a SetImagePresentationWithResponse call
func ParseSetImagePresentationResponse(rsp *http.Response) (*SetImagePresentationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetImagePresentationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseSetNetworkSettingsResponse parses an HTTP response from a SetNetworkSettingsWithResponse call
func ParseSetNetworkSettingsResponse(rsp *http.Response) (*SetNetworkSettingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetNetworkSettingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePushCapabilitiesResponse parses an HTTP response from a PushCapabilitiesWithResponse call
func ParsePushCapabilitiesResponse(rsp *http.Response) (*PushCapabilitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushCapabilitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AppliedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePushWallpaperConfigResponse parses an HTTP response from a PushWallpaperConfigWithResponse call
func ParsePushWallpaperConfigResponse(rsp *http.Response) (*PushWallpaperConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushWallpaperConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AppliedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseLoadWallpaperResponse parses an HTTP response from a LoadWallpaperWithResponse call
func ParseLoadWallpaperResponse(rsp *http.Response) (*LoadWallpaperResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoadWallpaperResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest AcceptedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON504 = &dest

	}

	return response, nil
}

// ParseSetParallaxResponse parses an HTTP response from a SetParallaxWithResponse call
func ParseSetParallaxResponse(rsp *http.Response) (*SetParallaxResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetParallaxResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseMoveParallaxResponse parses an HTTP response from a MoveParallaxWithResponse call
func ParseMoveParallaxResponse(rsp *http.Response) (*MoveParallaxResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MoveParallaxResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseSetPlaybackPolicyResponse parses an HTTP response from a SetPlaybackPolicyWithResponse call
func ParseSetPlaybackPolicyResponse(rsp *http.Response) (*SetPlaybackPolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetPlaybackPolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AppliedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetWallpaperStatusResponse parses an HTTP response from a GetWallpaperStatusWithResponse call
func ParseGetWallpaperStatusResponse(rsp *http.Response) (*GetWallpaperStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWallpaperStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePushWallpaperConfigLegacyResponse parses an HTTP response from a PushWallpaperConfigLegacyWithResponse call
func ParsePushWallpaperConfigLegacyResponse(rsp *http.Response) (*PushWallpaperConfigLegacyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushWallpaperConfigLegacyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AppliedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePushCapabilitiesLegacyResponse parses an HTTP response from a PushCapabilitiesLegacyWithResponse call
func ParsePushCapabilitiesLegacyResponse(rsp *http.Response) (*PushCapabilitiesLegacyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushCapabilitiesLegacyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AppliedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}
